{{- if (include "actions-runner.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "actions-runner.fullname" . }}
  labels:
    {{- include "actions-runner.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.github.username | b64enc | quote }}
  password: {{ .Values.github.password | b64enc | quote }}
{{- end }}
