name: ci

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: lazybit.ch

jobs:
  lint:
    name: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

  build:
    name: build
    needs: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${DOCKER_REGISTRY} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: |
          docker build --rm --build-arg UBUNTU_VERSION=20.04 -t ${DOCKER_REGISTRY}/actions-runner:latest .
          docker push ${DOCKER_REGISTRY}/actions-runner:latest
